### ISSUE TITLE
Not working with Swift 1.2

### ISSUE THREAD

**Issue by catherineschwartz** [lysannschlegel/GooglePlusShareActivity#11]
Hi,
Thanks for your plugin, it works great... except with XCode 6.3 and Swift 1.2. 
I had to copy the files in my project and link them in the Bridging-Header file (and add pod 'googleplus-ios-sdk' into my Podfile) to make it work. 
It's not an ideal solution, so I would be grateful if you could have a quick look :)
Thanks!

**Comment by lysannschlegel** [comment]
I just set up a Swift example project to look for issues with Xcode 6.3.
But everything seems to work fine...

Here's what I did:
* Started out with the "Single View Application" template, but ditched some unnecessary files from the template (storyboard etc).
* Copied the Podfile from the Objective-C example project and ran `pod install`
* Added an Objective-C bridging header and imported `<GooglePlus/GooglePlus.h>` as well as `<GooglePlusShareActivity/GPPShareActivity.h>`
* Translated the code from the Objective-C example project to Swift

And then it worked.
You can have a look at `Examples/Swift` to see the result and compare to what you tried in your setup.

If what I listed above isn't working for you, please describe your problem in more detail. Maybe I can be of more help then.

**Comment by catherineschwartz** [comment]
Hi, thanks for your reply. I still get the error on my project. It goes like this:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GPPShare", referenced from:
      objc-class-ref in GPPShareActivity.o
     (maybe you meant: _OBJC_CLASS_$_GPPShareActivity)
  "_OBJC_CLASS_$_GPPSignIn", referenced from:
      objc-class-ref in GPPShareActivity.o
  "_kGTLAuthScopePlusLogin", referenced from:
      -[GPPShareActivity performActivityInternal] in GPPShareActivity.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'll have a closer look anyway ;)

**Comment by lysannschlegel** [comment]
Looking at https://github.com/CocoaPods/CocoaPods/issues/3106 I suppose you have `use_frameworks!` in your Podfile. The linked issue describes that dependencies with bundled frameworks, such as the google-plus-ios-sdk, do not work with CocoaPods 0.36 when using frameworks to build the pods.

It looks like there will be a workaround in the future, but the only thing you can do right now is removing `use_frameworks!` ... unless of course you have Swift pods, then your current solution would be the only option until the issue is fixed.
